# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 一名广告狗的自白
description: 广告 机器学习 优化 # write a nice description for your blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "tongming.github.io" # the base hostname & protocol for your site http://www.example.com
# google_analytics: 'UA-XXXXXX-X'
weibo_username: 'tommink'
weibo_url: 'tomknuth'

# Build settings
markdown: kramdown

permalink: '/:title/'

gems: [jekyll-paginate]

paginate: 10
